import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {Space_Grotesk} from "next/font/google";
import Navbar from "@/src/components/general/Navbar";
import Footer from "@/src/components/general/Footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({
    subsets: ["latin", "latin-ext"],
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">

        <body
            className={`${spaceGrotesk.className} ${spaceGrotesk.className} antialiased min-h-screen flex flex-col`}
        >
        <Navbar/>
        <main className="flex-1">
            {children}
        </main>
        <Footer/>
        </body>
        </html>
    );
}
