services:
  backend:
    build: ./backend
    container_name: kicz-backend
    ports:
      - "8000:8000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
    volumes:
      - ./backend/data:/app/data
  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8000
    container_name: kicz-frontend
    ports:
      - "3000:3000"   # Next.js domyślnie
    depends_on:
      - backend